### ISSUE TITLE
not all tests run locally (master)

### ISSUE THREAD

**Issue by kmulvey** [gin-gonic/gin#314]
see out put of `go test -v` here:
https://gist.github.com/kmulvey/16dc3cc49ef58c5517c6

running in travis seems fine

**Comment by manucorporat** [comment]
weird....

**Comment by javierprovecho** [comment]
Can you post your system data? (architecture, OS,  GoLang ver...)

**Comment by kmulvey** [comment]
Fedora release 21
3.19.7-200.fc21.x86_64
go version go1.4.2 linux/amd64

running an single test also doesnt work but in a different way:

```
kmulvey@deepthought: gin > go test gin_test.go 
# command-line-arguments
./gin_test.go:20: undefined: SetMode
./gin_test.go:20: undefined: TestMode
./gin_test.go:24: undefined: New
./gin_test.go:32: undefined: HandlersChain
./gin_test.go:33: undefined: HandlersChain
./gin_test.go:34: undefined: HandlersChain
./gin_test.go:38: undefined: Default
./gin_test.go:43: undefined: Context
./gin_test.go:44: undefined: Context
./gin_test.go:46: undefined: New
./gin_test.go:46: too many errors
FAIL	command-line-arguments [build failed]

```

**Comment by nazwa** [comment]
Yup, can confirm I'm seeing the same errors.

`go version go1.4.2 windows/amd64`

**Comment by manucorporat** [comment]
I guess I know how to fix it... but this should not happen, in fact in my machine all the tests passes...
should we report this to the Go Team? [Assert](github.com/stretchr/testify/assert)?

I think the problem is that some archs have different implementations when comparing two values of different types.

```
int(63) == int32(63) 
my machine: true
your machine: false
```

any other idea?

**Comment by nazwa** [comment]
I was just writing about this. The problem is in how numbers are represented. 

context index is defined as `int8`, but on my x64 system numbers default to int64, so the comparison fails.

Changing the test to `assert.Equal(t, c.index, int8(-1))` fixes it, but it seems like a silly thing to do.

**Comment by manucorporat** [comment]
@nazwa right! in fact, the assert package we are using has two methods:
```
assert.Equal() // the type does not matter
assert.Exactly() // the type matters
```

**Comment by nazwa** [comment]
Not sure what to do about this. The only viable solution would be to update the testing package and check types of all standard types and cast (lol) to their x64 counterparts but that's just asking for more errors.

**Comment by nazwa** [comment]
Or in the short run, force type casts in all gin tests lol. I might go through them all if I have more time tonight.

**Comment by manucorporat** [comment]
@nazwa I just reported it, let's see what they say...
https://github.com/stretchr/testify/issues/174

**Comment by manucorporat** [comment]
@nazwa let's use int64 for everything hahaha it would be great to fix the root of the problem

**Comment by manucorporat** [comment]
this is hilarious:
type gin.HandlerFunc func(*gin.Context)

```
	Error:		Not equal: (gin.HandlerFunc)(0x4b0ab0) (expected)
			        != (func(*gin.Context))(0x4b0ab0) (actual)
```

even the address is the same :laughing:

**Comment by nazwa** [comment]
https://github.com/golang/go/blob/master/src/reflect/deepequal.go#L141

This is where it fails. I can see the reasoning behind it. If types are different then surely they `can't` match. Reminds me of php and "32" == 32. Are they the same, or not? 

Same with your handler function, can a closure be equal to a typed function? Maybe, maybe not :smiley:

**Comment by manucorporat** [comment]
@nazwa  LOL but... but... why does it work in my machine????

**Comment by manucorporat** [comment]
@nazwa  
```go
	if ObjectsAreEqual(expected, actual) {
		return true
	}

	actualType := reflect.TypeOf(actual)
	expectedValue := reflect.ValueOf(expected)
	if expectedValue.Type().ConvertibleTo(actualType) {
		// Attempt comparison after type conversion
		if reflect.DeepEqual(actual, expectedValue.Convert(actualType).Interface()) {
			return true
		}
	}

	return false
```

that should work...

**Comment by nazwa** [comment]
Maybe go compiler inlines all int8, int32 etc on the fly to int32 because they are handled identically on your system?

**Comment by manucorporat** [comment]
right right! but it still smells like a bug.
i am ok if the system handles it identically... but this is a cross platform high level language, this behaviour looks unacceptable to me...

**Comment by nazwa** [comment]
Yea, it's a bit frustrating. Let's just switch to node and not worry about any of that stupid typesafety stuff

**Comment by nazwa** [comment]
Things like `assert.Equal(t, cp.index, AbortIndex)` also fail because AbortIndex is untyped, so it defaults to system spec, while index is again, int8. No idea what to do about that.

PS
I had no idea people still use  32 bit systems haha

**Comment by manucorporat** [comment]
@nazwa Let's just switch to node and not worry about any of that stupid type safety stuff
hahaha who needs integers when you have floats? hahaha http://greweb.me/2013/01/be-careful-with-js-numbers/

**Comment by manucorporat** [comment]
this probably fixes some unit tests: https://github.com/gin-gonic/gin/commit/1228b03914ac7ec8f9ba8c17f599863b0e1883ea

**Comment by nazwa** [comment]
Ok, there is a genuine error on windows.
https://github.com/gin-gonic/gin/blob/master/routes_test.go#L164

Dir is always empty :) But it's to do with the path library hardcoding the "/" separator. I'll report that in a bit.

**Comment by nazwa** [comment]
Ha! ok, it needs updating in gin - https://github.com/golang/go/issues/7698#issuecomment-66093258

**Comment by manucorporat** [comment]
nice! thanks. can you try if it works?

**Comment by nazwa** [comment]
Yup. 
import "path/filepath"

`dir, filename := filepath.Split(f.Name())`

**Comment by manucorporat** [comment]
Fixed: https://github.com/gin-gonic/gin/commit/0d5dc25d39e49efc1ae5a0683562b159c76b184c

**Comment by nazwa** [comment]
Also: https://github.com/gin-gonic/gin/blob/master/path_test.go#L86

`AllocsPerRun` returns float64, so this needs to be: `assert.Equal(t, allocs, float64(0))`

*(no point in doing a PR just for that one :smile:)*


That solves all fails except for the
```
Not equal: (gin.HandlerFunc)(0x4b9f50) (expected)
                                != (func(*gin.Context))(0x4b9f50) (actual)
```

I tried casting it `assert.Equal(t, router.allNoMethod[2], HandlerFunc(middleware0))` but it still fails. Nice one GO!

**Comment by manucorporat** [comment]
really??? does `assert.Equal(t, router.allNoMethod[2], HandlerFunc(middleware0))` fail?
wow, that's bad!!

I will try to fix all this later, we need to investigate it before committing an issue in golang/go.

**Comment by nazwa** [comment]
```
        Location:       gin_test.go:146
        Error:          Not equal: (gin.HandlerFunc)(0x4b9f90) (expected)
                                != (gin.HandlerFunc)(0x4b9f90) (actual)
```

**Comment by manucorporat** [comment]
WOW, that DOES NOT make any sense. this remind me one situation when we discovered a bug, and the same day, everything started falling apart. Nothing worked any more haha

**Comment by nazwa** [comment]
Haha, well, it does work, just shouldn't (at least according to the above :smile:)

**Comment by manucorporat** [comment]
@nazwa  WTF!!

```go
package main

import (
	"fmt"
	"reflect"
)

type Struct struct{}

func main() {
	a := func(_ *Struct) {}
	fmt.Println(reflect.DeepEqual(a, a))
}
```
```
false
```

**Comment by manucorporat** [comment]
@nazwa @kmulvey I think it is fixed: https://github.com/gin-gonic/gin/commit/766493c916ec2e5c63faa42e1425bcd6b598d014
